# Generated by Django 6.0.6 on 2026-06-20 08:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('discount', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to='media/images')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to='media/images/')),
                ('video', models.FileField(upload_to='media/video/')),
                ('release', models.DateTimeField(default=datetime.datetime.now)),
                ('file', models.FileField(upload_to='goods_files/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('goods_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.goods')),
            ],
            bases=('game.goods',),
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('goods_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.goods')),
                ('grade', models.CharField(choices=[('UC', 'Uncommon'), ('CM', 'Common'), ('RR', 'Rare'), ('SR', 'Superrare'), ('EP', 'Epic'), ('MT', 'Mythic'), ('AC', 'Arcane'), ('LG', 'Legend')], default='UC', max_length=2)),
            ],
            bases=('game.goods',),
        ),
        migrations.AddField(
            model_name='goods',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.user'),
        ),
    ]
